### ISSUE TITLE
How to style ?

### ISSUE THREAD

**Issue by Archetipo95** [icyz/zurb-foundation6-multiselect#1]
I'm having troubles with css styling.

For example I can't color text.

Or I can't use a scrollable overflow.

Can you help me?

**Comment by icyz** [comment]
Yes, but what do you means? Try to post your change here.
Try to brutally add `color: red;` inside .zselect class: it will change the text color.

**Comment by Archetipo95** [comment]
Thanks color is working I was styling a old css .... *stupid me*

What can you tell me for the overflow ? I have a very big list of elements and it's overflowing.

**Comment by Archetipo95** [comment]
Solved thank you! I was editing and old css style..... *STUPID ME*
