### ISSUE TITLE
attribute "rel"

### ISSUE THREAD

**Issue by jaycci** [icyz/zurb-foundation6-multiselect#3]
The code generates a "div.zselect" that reflects the contents of the "select" written in the HTML. This "div.zselect" has a unique ID, automatically generated by the JavaScript code. But the "select" element is altered with a "rel" attribute, related to the ID of the "div.zselect".
"rel" is an attribute for links only. Not for other elements. And it has a specific syntax (for example, its value cannot start by a digit).

So I recommend that "rel" attribute be replaced by "data-rel", as specified by W3 specification (https://www.w3.org/TR/html/dom.html#embedding-custom-non-visible-data-with-the-data-attributes).

**Comment by icyz** [comment]
Yes, I know and you're right ;-) 
Actually I'm a bit busy, but I will replace "rel" soon.
Thanks for your interesting

**Comment by jaycci** [comment]
And thanks for your code!

**Comment by icyz** [comment]
I've already replaced it, according with W3 spec
