### ISSUE TITLE
opening the multiselect closes it immediately

### ISSUE THREAD

**Issue by jaycci** [icyz/zurb-foundation6-multiselect#4]
When I click on the multiselect element I've just created, it receives 2 events. And the second event thinks it's a "click out of the element so as to close it". So the element opens and closes itself.

I don"t understand the test on line 83 "if (container.parent().is(e.target) || container.prev().is(e.target) || ( container.is(':visible') && !container.parent().is(e.target) ) && ( container.has(e.target).length === 0 ))"

I've replaced it by "if (container.parent().is(e.target) || container.prev().is(e.target) || ( container.is(':visible') && !(e.target.tagName == 'SELECT') ) && ( container.has(e.target).length === 0 ))".

(Firefox 56.0.2 on MacOS)

**Comment by icyz** [comment]
It fix the problem? 
I've tried, but I can't reproduce that issue. Now I'm on windows 10, will try on macos in my office.

**Comment by jaycci** [comment]
It solves the problem, yes. But I don't know why you tested "( container.is(':visible') && !container.parent().is(e.target) )", thus my modification may break something elsewhere.

**Comment by icyz** [comment]
I had rewrite this plugin from old code (I was started this plugin for F4) for our CMS. And I'm always in lack-of-time-state.
I have to check  :-)

**Comment by icyz** [comment]
I have tried firefox 56.0.2 (64 bit) and it works (on macOS)
I also tried with firefox quantum 57.0 (64 bit) and it works (macOS)

Feel free to reopen this if you still have the issue
