### ISSUE TITLE
objets ID should not start with a digit

### ISSUE THREAD

**Issue by jaycci** [icyz/zurb-foundation6-multiselect#5]
HTML norm says that an ID can start with a digit. But everything else in the HTML world does not like ID starting with a digit (CSS, jQuery...)n, it has to be escaped.
I suggest that the automatic generated ID of the objects start with a letter instead of a random character in class [a-z0-9].
Replace :
`id = Math.random().toString(36).substr(2, 9);`
with :
`id = "a" + Math.random().toString(36).substr(2, 9);`
for example.

**Comment by icyz** [comment]
added char "z" before autogenerated random id
